export const CATEGORIES = [
  { id: "all", label: "Усі товари" },
  { id: "deck-boxes", label: "Deck Boxes" },
  { id: "animal-deck-boxes", label: "Animal Deck Boxes" },
  { id: "mtg-counters", label: "MTG Counters" },
  { id: "dice-life", label: "Dice + Life Counter" },
];

// Кожна категорія товарів прив'язана до кольору мани MTG,
// щоб картки товарів виглядали як справжні ігрові карти.
export const CATEGORY_STYLE = {
  "deck-boxes": {
    color: "#b8b0a1",
    dark: "#4b4638",
    typeLine: "Артефакт — Deck Box",
  },
  "animal-deck-boxes": {
    color: "#3f7d3a",
    dark: "#1d3a1a",
    typeLine: "Істота — Тварина",
  },
  "mtg-counters": {
    color: "#e8e2c8",
    dark: "#8a8262",
    typeLine: "Чари — Лічильник",
  },
  "dice-life": {
    color: "#3b6fb0",
    dark: "#1c3352",
    typeLine: "Артефакт — Кубики",
  },
};

export const RARITY_STYLE = {
  common: { label: "Звичайна", color: "#6b7280" },
  uncommon: { label: "Незвичайна", color: "#b6c2cc" },
  rare: { label: "Рідкісна", color: "#d4af37" },
  mythic: { label: "Міфічна", color: "linear-gradient(135deg,#ff8a3d,#d9480f)" },
};

export const PRODUCTS = [
  {
    id: "dark-wizard-tower",
    title: "Dark Wizard Tower Deck Box, MTG Commander",
    category: "deck-boxes",
    rarity: "mythic",
    price: 29.25,
    originalPrice: 39.0,
    icon: "🗼",
    gradient: "linear-gradient(135deg,#1f2233,#3a3f63)",
    badge: "Хіт продажів",
    rating: 5.0,
    reviews: 214,
  },
  {
    id: "mega-buster-sword",
    title: "MEGA Buster Sword Card Holder | Final Fantasy inspired",
    category: "deck-boxes",
    rarity: "mythic",
    price: 225.0,
    originalPrice: 300.0,
    icon: "⚔️",
    gradient: "linear-gradient(135deg,#374151,#6b7280)",
    badge: "Преміум",
    rating: 5.0,
    reviews: 42,
  },
  {
    id: "commander-100",
    title: "MTG Commander Deck Box 100+ Double Sleeved",
    category: "deck-boxes",
    rarity: "uncommon",
    price: 41.25,
    originalPrice: 55.0,
    icon: "📦",
    gradient: "linear-gradient(135deg,#1d4ed8,#f59e0b)",
    rating: 4.9,
    reviews: 331,
  },
  {
    id: "happy-meal",
    title: "Happy Meal MTG Deck Box: Magic Card Holder",
    category: "deck-boxes",
    rarity: "rare",
    price: 33.75,
    originalPrice: 45.0,
    icon: "🍔",
    gradient: "linear-gradient(135deg,#dc2626,#fbbf24)",
    badge: "Улюблене",
    rating: 5.0,
    reviews: 128,
  },
  {
    id: "fiery-eye-tower",
    title: "Dark Tower Deck Box with Fiery Eye, MTG",
    category: "deck-boxes",
    rarity: "uncommon",
    price: 37.5,
    originalPrice: 50.0,
    icon: "🔥",
    gradient: "linear-gradient(135deg,#111827,#7c2d12)",
    rating: 4.8,
    reviews: 96,
  },
  {
    id: "mtg-wolf",
    title: "MTG Wolf Deck Box Compatible with Commander",
    category: "animal-deck-boxes",
    rarity: "uncommon",
    price: 42.74,
    originalPrice: 56.99,
    icon: "🐺",
    gradient: "linear-gradient(135deg,#334155,#94a3b8)",
    rating: 4.9,
    reviews: 77,
  },
  {
    id: "trash-raccoon",
    title: "Trash Raccoon Rat Deck Box – Holds 100+",
    category: "animal-deck-boxes",
    rarity: "rare",
    price: 37.5,
    originalPrice: 50.0,
    icon: "🦝",
    gradient: "linear-gradient(135deg,#4b5563,#9ca3af)",
    badge: "Кумедне",
    rating: 4.8,
    reviews: 53,
  },
  {
    id: "rabbit-tree-stump",
    title: "Rabbit Deck Box | Tree Stump Design",
    category: "animal-deck-boxes",
    rarity: "uncommon",
    price: 41.25,
    originalPrice: 55.0,
    icon: "🐇",
    gradient: "linear-gradient(135deg,#78350f,#a16207)",
    rating: 5.0,
    reviews: 61,
  },
  {
    id: "dragon-egg-dice-tower",
    title: "Dragon Egg Dice Tower + Life Counter Set",
    category: "dice-life",
    rarity: "rare",
    price: 28.5,
    originalPrice: 38.0,
    icon: "🐲",
    gradient: "linear-gradient(135deg,#065f46,#10b981)",
    badge: "Новинка",
    rating: 4.9,
    reviews: 34,
  },
  {
    id: "spellbook-counter",
    title: "Spellbook MTG Counter Tracker (Set of 2)",
    category: "mtg-counters",
    rarity: "common",
    price: 18.75,
    originalPrice: 25.0,
    icon: "📖",
    gradient: "linear-gradient(135deg,#4c1d95,#8b5cf6)",
    rating: 4.7,
    reviews: 22,
  },
];
